import type { Exercise } from '../../types';

// priming — Phase 3 densification batch.
export const primingP3Exercises: Exercise[] = [
  {
    id: 'pr-p3-1',
    type: 'scenario-quiz',
    difficulty: 'expert',
    question: {
      de: 'Mehrere Techniken wirken hier gleichzeitig. Welche erklärt am besten, warum die Belegschaft die Umstrukturierung von sich aus als „Chance" und „Wachstum" beschreibt — obwohl die Ankündigung inhaltlich überwiegend neutrale bis negative Veränderungen enthielt?',
      en: 'Several techniques are at work at once here. Which one best explains why the workforce spontaneously describes the reorganization as an "opportunity" and "growth" — even though the substance of the announcement was mostly neutral-to-negative change?',
    },
    scenario: {
      de: 'Ein Konzern muss eine unpopuläre Umstrukturierung ankündigen: Mehrere Teams werden zusammengelegt, ein Teil der Rollen fällt weg oder verändert sich. Die interne Kommunikation baut das Town-Hall so auf: Die ersten fünfzehn Minuten — noch bevor das Wort Umstrukturierung überhaupt fällt — feiert der CEO Mitarbeitende, die sich beruflich neu erfunden haben: eine Pflegekraft, die heute Datenanalystin ist, ein Lagerleiter, der jetzt Trainer ist. Auf den Folien und in der Erzählung tauchen dabei immer wieder dieselben Begriffe auf: „wachsen", „Chance", „neues Kapitel", „sich neu erfinden". Erst danach folgt die eigentliche Ankündigung, nüchtern vorgetragen. Ein FAQ-Slide betont, „nur 6 % der Rollen" seien betroffen; eine weitere Folie erwähnt, „drei unserer größten Wettbewerber haben bereits letztes Jahr umstrukturiert". In der Puls-Umfrage direkt danach beschreiben auffällig viele die Umstrukturierung von sich aus als „Chance" und „Wachstum" — auch Mitarbeitende, deren Rolle tatsächlich wegfällt. In Nachgesprächen kann kaum jemand eine konkrete Zusage benennen, die ihnen persönlich Wachstum versprochen hätte; sie „kamen einfach mit dem Gefühl heraus, dass es um Chancen geht".',
      en: 'A corporation has to announce an unpopular reorganization: several teams are being merged, and some roles are cut or changed. Internal comms structures the town hall as follows: the first fifteen minutes — before the word "reorganization" is even said — the CEO celebrates employees who reinvented their careers: a nurse who is now a data analyst, a warehouse lead who is now a trainer. Across the slides and the storytelling, the same words keep recurring: "grow", "opportunity", "new chapter", "reinvent yourself". Only afterwards comes the actual announcement, delivered plainly. A FAQ slide stresses that "only 6% of roles" are affected; another slide notes that "three of our largest competitors already reorganized last year". In the pulse survey immediately afterwards, a striking number spontaneously describe the reorganization as an "opportunity" and "growth" — including employees whose roles are in fact being eliminated. In follow-up conversations, almost no one can name a concrete commitment that promised them personal growth; they "just came out with the feeling that it is about opportunities".',
    },
    options: [
      { de: 'Priming', en: 'Priming' },
      { de: 'Framing', en: 'Framing' },
      { de: 'Soziale Bewährtheit (Social Proof)', en: 'Social proof' },
      { de: 'Emotionaler Appell', en: 'Emotional appeal' },
    ],
    correctAnswers: [0],
    explanation: {
      de: 'Dominanter Treiber ist Priming. Das Eröffnungssegment installiert — über die wiederholten Begriffe „wachsen", „Chance", „neues Kapitel" und die Neuerfindungs-Geschichten — das semantische Konzept „persönliche Chance/Wachstum" im Gedächtnis. Dieses Konzept bleibt kognitiv präsent und färbt die kurz darauf angekündigte, eigentlich unabhängige Umstrukturierung ein. Die entscheidenden Belege dafür, dass es Priming ist und nicht die anderen Hebel: Die Aktivierung passiert, bevor das Thema überhaupt genannt wird; der Effekt zeigt sich als Übertrag auf ein späteres, sachlich unverbundenes Urteil; die Leute nennen genau die vor-installierten Begriffe; und niemand kann eine inhaltliche Zusage benennen — selbst Betroffene, deren Rolle wegfällt, greifen zum Konzept „Chance". Ethische Grenze: Ein ehrliches, hoffnungsvolles Eröffnungssegment ist legitim, wenn die Umstrukturierung tatsächlich Entwicklungswege eröffnet und die geweckte Assoziation die Realität spiegelt; manipulativ wird es, wenn ein „Chancen"-Heiligenschein erzeugt wird, den die konkreten Veränderungen (Rollenverluste) nicht einlösen, und der die Aufmerksamkeit von der Substanz weglenkt. Warum die anderen nicht dominieren: Framing ist präsent — „nur 6 % der Rollen" ist dieselbe Tatsache in minimierender Verpackung —, aber Framing formt die Darstellung der Umstrukturierung selbst (ihr Ausmaß) und erklärt weder den Übertrag aus einem thematisch fremden Eröffnungssegment noch, warum ausgerechnet Betroffene spontan „Chance" sagen. Soziale Bewährtheit steckt im Hinweis auf die Wettbewerber, normalisiert aber nur die Entscheidung des Unternehmens („andere tun es auch") — sie zielt auf „sollte man das tun", nicht auf das persönliche Konzept „das ist meine Chance". Ein emotionaler Appell würde ein gewecktes Gefühl direkt auf eine Handlung lenken; hier wird jedoch kein Appell ausgesprochen, und gemessen wird ein semantisches Etikett („Chance/Wachstum"), das vorab installiert wurde und sich auf ein späteres Urteil überträgt — Priming setzt ein Konzept, der emotionale Appell zieht am Gefühlshebel, um eine Entscheidung zu treiben.',
      en: 'The dominant driver is priming. The opening segment installs — through the repeated words "grow", "opportunity", "new chapter" and the reinvention stories — the semantic concept "personal opportunity/growth" in memory. That concept stays cognitively accessible and colours the reorganization announced moments later, which is otherwise an unrelated judgment. The decisive evidence that this is priming rather than the other levers: the activation happens before the topic is even named; the effect shows up as a carry-over onto a later, substantively unconnected judgment; people report exactly the pre-installed words; and no one can name any substantive commitment — even affected employees whose roles are cut reach for the concept "opportunity". Ethical boundary: an honest, hopeful opening is legitimate when the reorganization genuinely opens development paths and the evoked association mirrors reality; it becomes manipulative when it manufactures an "opportunity" halo that the concrete changes (role losses) do not deliver and that steers attention away from the substance. Why the others do not dominate: framing is present — "only 6% of roles" is the same fact in a minimizing wrapper — but framing shapes how the reorganization itself (its magnitude) is presented, and explains neither the carry-over from a thematically foreign opening segment nor why affected employees in particular spontaneously say "opportunity". Social proof sits in the competitor note, but it merely normalizes the company\'s decision ("others do it too") — it targets "should the company do this", not the personal concept "this is my chance". An emotional appeal would channel an aroused feeling directly toward an action; but here no appeal is made, and what is measured is a semantic label ("opportunity/growth") that was pre-installed and carries over to a later judgment — priming plants a concept, whereas an emotional appeal pulls the feeling-lever to drive a decision.',
    },
    points: 20,
    primaryTechniqueId: 'priming',
    relatedTechniques: ['priming', 'framing', 'social_proof'],
  },
];
